package ru.berkut.spring.hubflow.enums;
public enum NotificationType {
    NEW_WEEK, CHECKPOINT_DEADLINE, SESSION_BOOKED,
    SESSION_REMINDER, VOTE_OPEN, MENTOR_FEEDBACK, APPLICATION_REVIEWED , TEAM_INVITE ,
    TEAM_INVITE_ACCEPTED, TEAM_INVITE_DECLINED
}
